package com.example.tibcomigrationclassgenerator;

import com.example.tibcomigrationclassgenerator.model.APIHeader;
import com.example.tibcomigrationclassgenerator.model.ListOfBankBranchInqRq;
import com.example.tibcomigrationclassgenerator.model.MLI_0087_Req_Record;
import org.mapstruct.Context;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

@Mapper(componentModel = "spring")
public abstract class MLI_0087_Req_Record_Mapper_AutoGenerated {

    @Mapping(target = "mli_0087_req_termid", source = "source", qualifiedByName = "mapMli_0087_req_termid")
    @Mapping(target = "mli_0087_req_org", source = "source", qualifiedByName = "mapMli_0087_req_org")
    @Mapping(target = "mli_0087_req_org_inner", constant = "78")
    @Mapping(target = "mli_0087_re0_user_id", source = "branchOrgCode")

    public abstract MLI_0087_Req_Record map(ListOfBankBranchInqRq source, @Context APIHeader apiHeader);

    @Named("mapMli_0087_req_termid")
    public String mapMli_0087_req_termid(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic: concat(substring($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:TerminalID,1,8), substring($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:DestCountryCode,1,2))
        // Java Condition Logic: 
        // javaConditionLogic has remaked, Will turn on this feature later
    }

    @Named("mapMli_0087_req_org")
    public String mapMli_0087_req_org(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic:        if($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:ChannelID = 'CITI'){
//       $Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:OrgCode
//      }
//       if($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:ChannelID = 'SG'){
//       $Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:OrgCode
//      }
//       else{
//       0
//      }
//
        // Java Condition Logic: 
        // javaConditionLogic has remaked, Will turn on this feature later
    }

    @Named("mapMli_0087_req_org_inner")
    public String mapMli_0087_req_org_inner(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic:        if($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:ChannelID = 'CITI'){
//       if($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:OrgCode = '3'){
//       78
//      }
//     }
//       if($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:ChannelID = 'SG'){
//       if($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:OrgCode = '5'){
//       998
//      }
//     }
//
        // Java Condition Logic: 
        // javaConditionLogic has remaked, Will turn on this feature later
    }
}
