package com.example.tibcomigrationclassgenerator;

import com.example.tibcomigrationclassgenerator.model.APIHeader;
import com.example.tibcomigrationclassgenerator.model.ListOfBankBranchInqRq;
import com.example.tibcomigrationclassgenerator.model.MLI_0087_Req_Record;
import org.mapstruct.Context;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

@Mapper(componentModel = "spring")
public abstract class MLI_0087_Req_Record_Mapper_AutoGenerated {

    @Mapping(target = "mli_0087_req_mesg_id", constant = "0087")
    @Mapping(target = "mli_0087_req_ver_no", constant = "11")
    @Mapping(target = "mli_0087_req_termid", source = "source", qualifiedByName = "mapMli_0087_req_termid")
    @Mapping(target = "mli_0087_re0_user_id", source = "source", qualifiedByName = "mapMli_0087_re0_user_id")
    @Mapping(target = "mli_0087_req_dte_time", source = "source", qualifiedByName = "mapMli_0087_req_dte_time")
    @Mapping(target = "mli_0087_req_action_cd", source = "source", qualifiedByName = "mapMli_0087_req_action_cd")
    @Mapping(target = "mli_0087_req_org", source = "source", qualifiedByName = "mapMli_0087_req_org")
    @Mapping(target = "mli_0087_req_bkbr_number", source = "source", qualifiedByName = "mapMli_0087_req_bkbr_number")

    public abstract MLI_0087_Req_Record map(ListOfBankBranchInqRq source, @Context APIHeader apiHeader);

    @Named("mapMli_0087_req_termid")
    public String mapMli_0087_req_termid(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic: concat(substring($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:TerminalID,1,8), substring($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:DestCountryCode,1,2))
        return null;
    }

    @Named("mapMli_0087_re0_user_id")
    public String mapMli_0087_re0_user_id(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic: $Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:UserID
        return null;
    }

    @Named("mapMli_0087_req_dte_time")
    public String mapMli_0087_req_dte_time(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic: if (esbparam:getDataForTwoKeys('isDateTimeConversionRequired', $Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:ChannelID, $Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:DestCountryCode) = 'Y') then esbcustom:convertECSRequest('DT','DT',esbcustom:getCurrentDatetime($Start/root/pfx4:RqHeader/pfx4:ClientDetails/pfx4:DestCountryCode)) else esbcustom:convertECSRequest('DT','DT',$Start/root/pfx4:RqHeader/pfx4:DateAndTimeStamp)
        // Java Condition Logic: 
        return null;
    }

    @Named("mapMli_0087_req_action_cd")
    public String mapMli_0087_req_action_cd(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic: if (string-length(tib:trim($Start/root/pfx12:ListOfBankBranchInqRq/pfx12:BankBranchNo)) = 0) then '02' else '01'
        // Java Condition Logic: 
        return null;
    }

    @Named("mapMli_0087_req_org")
    public String mapMli_0087_req_org(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic: $Start/root/pfx12:ListOfBankBranchInqRq/pfx12:BranchOrgCode
        // Java Condition Logic: 
        return null;
    }

    @Named("mapMli_0087_req_bkbr_number")
    public String mapMli_0087_req_bkbr_number(ListOfBankBranchInqRq source, @Context APIHeader apiHeader) {
        // Tibco Logic: if (string-length(tib:trim($Start/root/pfx12:ListOfBankBranchInqRq/pfx12:ListRq/StartIndex)) != 0) then $Start/root/pfx12:ListOfBankBranchInqRq/pfx12:ListRq/StartIndex else if (exists($Start/root/pfx12:ListOfBankBranchInqRq/pfx12:BankBranchNo) and string-length($Start/root/pfx12:ListOfBankBranchInqRq/pfx12:BankBranchNo) > 0) then $Start/root/pfx12:ListOfBankBranchInqRq/pfx12:BankBranchNo else '0'
        // Java Condition Logic: 
        return null;
    }
}
